"""Add cascade delete for user messages

Revision ID: 14d79ec453a6
Revises: 443367a72cad
Create Date: 2025-11-10 23:07:28.985070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14d79ec453a6'
down_revision = '443367a72cad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('message_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('message_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['sender_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['recipient_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('message_ibfk_2'), 'user', ['recipient_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('message_ibfk_1'), 'user', ['sender_id'], ['id'])

    # ### end Alembic commands ###
