"""Add Message model

Revision ID: 270ab0edbc12
Revises: 
Create Date: 2025-11-10 16:34:49.780879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '270ab0edbc12'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('sender_id', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('recipient_id', mysql.VARCHAR(length=36), nullable=True),
    sa.Column('subject', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('body', mysql.TEXT(), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('is_read', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('is_broadcast', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['recipient_id'], ['user.id'], name=op.f('messages_ibfk_1')),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name=op.f('messages_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
