"""se modifico el modelo del paso

Revision ID: 33248660dbb5
Revises: 49d351948666
Create Date: 2025-11-11 15:33:26.885897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33248660dbb5'
down_revision = '49d351948666'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pasos', schema=None) as batch_op:
        batch_op.alter_column('actualizado',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pasos', schema=None) as batch_op:
        batch_op.alter_column('actualizado',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
